MODEL_NAME = "microsoft/deberta-v3-base"
MAX_LENGTH_TOKENS = 256
NUM_CLASSES = 3

PATH = "taskADeBERTa/"
TRAIN_PATH = "train_json"
DEV_PATH = "dev_json"
NORMALIZED_PREFIX_FILE = "NORM"
NORMALIZED_TRAIN_FILE = PATH + NORMALIZED_PREFIX_FILE + "_TRAIN/"
NORMALIZED_DEV_FILE = PATH + NORMALIZED_PREFIX_FILE + "_DEV/"
NORMALIZED_SUFIX_FILE = "obj_"

BATCH_SIZE = 128
NUM_EPOCHS = 300