MODEL_NAME = "google/electra-base-discriminator"
MAX_LENGTH_TOKENS = 256
NUM_CLASSES = 3

PATH = "taskAElectra/"
TRAIN_PATH = "train_json"
DEV_PATH = "dev_json"
NORMALIZED_PREFIX_FILE = "NORM"
NORMALIZED_TRAIN_FILE = PATH + NORMALIZED_PREFIX_FILE + "_TRAIN/"
NORMALIZED_DEV_FILE = PATH + NORMALIZED_PREFIX_FILE + "_DEV/"
NORMALIZED_SUFIX_FILE = "obj_"

BATCH_SIZE = 256
NUM_EPOCHS = 300