brasileirao = ('Palmeiras', 'Santos', 'Vasco', 'Grêmio', 'Flamengo', 'Corinthians', 'Internacional', 'Cruzeiro', 'São Paulo', 'Atlético Mineiro', 'Botafogo', 'Fluminense', 'Coritiba', 'Bahia', 'Goiás', 'Guarani', 'Sport', 'Portuguesa', 'Atlético Paranaense', 'Vitória')
cont = 0
flamengo = brasileirao.index('Flamengo')
print('-=-' * 20)
print(f'Lista de times do Brasileirão: {brasileirao}')
print('-=-' * 20)
print(f'Os primeiros 5ª colocados são: {brasileirao[:5]}.')
print('-=-' * 20)
print(f'Os ultimos 4ª colocados são: {brasileirao[-1:-5:-1]}.')
print('-=-' * 20)
print(f'Times em ordem alfabética: {sorted(brasileirao)}')
print('-=-' * 20)
print(f'O time Flamengo está na {flamengo + 1}ª posição.')
print('-=-' * 20)
