nome=str(input('Digite seu nome completo: ')).strip()
print('Seu nome em maiúsculas fica {}'.format(nome.upper()))
print('Seu nome em minúsculas fica {}'.format(nome.lower()))
print('Seu nome tem ao todo {} letras'.format(len(nome)-nome.count(' ')))
corte=nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(corte[0],len(corte[0])))